### ISSUE TITLE
When used on GCE with gce_sd_config discovery scrape config, the ProtectHome=Yes option prevents Prometheus to discover Google Cloud Instances

### ISSUE THREAD

**Issue by michalklempa** [cloudalchemy/ansible-prometheus#153]
When this role is used provision an instances on GCE and this instance is desired to auto-discover other instances in GCE using the https://prometheus.io/docs/prometheus/latest/configuration/configuration/#gce_sd_config the implicit authentication mechanism (https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go) fails due not finding the well-known auth file in user home directory.
The auth file cannot be accessed due to systemd service file is using Sandboxing (https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Sandboxing), the ProtectHome=Yes option si the cause.

Steps to reproduce:
1. Provision a GCE instance using this role, have the instance with service account.
2. Use gce_sd_config discovery in use, for example use variable:
```
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
        - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"

 - job_name: "gce_instances"
    gce_sd_configs:
      project: "my-test-project"
      zone: us-central1-c
      port: 9100
```
3. Start Prometheus

Expected behavior:
- Prometheus should authenticate itself to GCE API using the findDefaultCredentials function using the fallback to use associated service account - as described here: https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go and in comment here: https://github.com/golang/oauth2/blob/master/google/go19.go#L38

Current behavior:
- Function findDefaultCredentials(https://github.com/golang/oauth2/blob/master/google/default.go#L43), fails at step 2. It tries to open the well-known credentials file (/home/prometheus/.config/gcloud/application_default_credentials.json in this case). This fails due to Permission Denied error returner from OS.
- Permission Denied is caused by Sandboxing from systemd, this error is returned even if the homedir exists with correct permissions and file in place.
- This relates to https://github.com/golang/oauth2/issues/337

To circumvent the https://github.com/golang/oauth2/issues/337 issue, let me propose one of two solutions:
1. set Sandboxing to read-only in systemd
2. set /tmp and the prometheus user home directory
