### ISSUE TITLE
Better handling of alerting rules

### ISSUE THREAD

**Issue by paulfantom** [cloudalchemy/ansible-prometheus#2]
Looking at alert rules in prometheus 1.x and 2.x it seems that we could define alerting rules in yaml (like in prometheus 2.x) and use jinja templates to create rules compatible with prometheus 2.x.

Take this config for example:
```
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      summary: Instance {{ $labels.instance }} down
```
it should easily map to v1:
```
ALERT InstanceDown
  IF up == 0
  FOR 5m
  LABELS { severity = "critical" }
  ANNOTATIONS {
    summary = "Instance {{ $labels.instance }} down",
    description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.",
  }
```

Also this way we can get rid of static alerting rules, and create them with jinja templates.

@rdemachkovych what do you think?
