### ISSUE TITLE
Use systemd for service control

### ISSUE THREAD

**Issue by SuperQ** [cloudalchemy/ansible-prometheus#25]
Since the role already assumes systemd service units, it would be better to declare them with the [systemd](http://docs.ansible.com/ansible/latest/systemd_module.html) rather than `service`.  The service module does not understand  or automatically run `daemon-reload`.

**Comment by paulfantom** [comment]
We are doing it, look here: https://github.com/cloudalchemy/ansible-prometheus/blob/master/handlers/main.yml
However currently there is a bug in ansible systemd module, which causes failures in idempotency testing when enabling service, that's why we use `service` module here: https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/main.yml#L8

**Comment by SuperQ** [comment]
I haven't noticed any issues with:

```
- name: Enable and start prometheus service
  systemd:
    name: prometheus.service
    state: started
    enabled: yes
    daemon_reload: yes
```

Is there an upstream bug?
