### ISSUE TITLE
Dynamically populate multiple targets from a variable

### ISSUE THREAD

**Issue by obitech** [cloudalchemy/ansible-prometheus#250]
Hey, sorry if this is more of an Ansible / Jinja related question but I've been struggling for a while with this. Please let me know if this is not the right place to ask this.

I want to set multiple targets from a variable that is in form of a list (my inventory, essentially):

```json
"groups": {
    "all": [
        "10.0.0.1", 
        "10.0.0.2", 
        "10.0.0.3"
    ], 
    "db": [
        "10.0.0.2", 
        "10.0.0.3"
    ], 
    "grafana": [
        "10.0.0.1"
    ], 
    "prometheus": [
        "10.0.0.1"
    ],
}
```

I tried:

```yaml
prometheus_targets:
  databases:
    - targets: "{{ groups['db'] | to_nice_yaml(indent=4) }}"

prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "databases"
    file_sd_configs:
      - files:
        - "{{ prometheus_config_dir }}/file_sd/databases.yml"
```

But this will get the indentation wrong:

```yaml
$ cat databases.yml
- targets: '- 10.0.0.2

    - 10.0.0.3

    '
```

Is there any way I can configure targets dynamically with this role?

**Comment by paulfantom** [comment]
Here is an example of such config: https://github.com/cloudalchemy/demo-site/blob/master/group_vars/all/vars#L12-L16

**Comment by obitech** [comment]
Thank you! Using your example solved it:

```yaml
prometheus_targets:
  databases:
    - targets:
        "{{ groups['db'] | map('regex_replace', '$', ':9104') |list }}"
```

```yaml
$ cat databases.yml 
- targets:
  - 10.0.0.2:9104
  - 10.0.0.3:9104
```
