### ISSUE TITLE
Customize the service file with an Ansible variable

### ISSUE THREAD

**Issue by paretl** [cloudalchemy/ansible-prometheus#270]
**What is missing?**

Add a limit of memory on Prometheus by using Systemd:
`MemoryLimit=6357M` in the service file

OR

Being able to add custom configuration in the service file with an Ansible variabke

**Why do we need it?**

In my case, and I think I'm not alone, I would like to customize the service file

**Environment**

* Role version:

I use the latest version of Prometheus and also of the role

* Ansible version information:

2.9.2

**Anything else we need to know?**:

Is it a good idea ?
I'm interested to have your feedback on it

**Comment by paulfantom** [comment]
> I would like to customize the service file

This can be done by using existing systemd mechanisms. You need to create directory `/etc/systemd/system/prometheus.service.d` and put your overrides there. The whole mechanism is explained in https://www.freedesktop.org/software/systemd/man/systemd.unit.html (search for "drop-in" directory).

Due to the complexity that systemd service files can have, I don't think that providing an option to configure all options with ansible variables is a solution that can be supported in the long term.

---
Simple playbook which can provide such customization can look like this:
```yaml
- hosts: prometheus
  become: yes
  handlers:
  - name: prometheus restart
    systemd:
      name: prometheus.service
      state: restarted
      enabled: yes
  roles:
  - cloudalchemy.prometheus
  tasks:
  - name: create drop-in directory
    file:
      path: "/etc/systemd/system/prometheus.service.d"
      state: directory
  - name: add prometheus service customizations
    copy:
      src: prometheus-override.conf
      dest: "/etc/systemd/system/prometheus.service.d/override.conf"
    notify: prometheus restart
```

So adding 3 tasks on a playbook level add a simple solution to all current and future options provided by systemd and additionally allows users to override safe defaults provided by this role.
