### ISSUE TITLE
What is http://status:9090/metrics ? 

### ISSUE THREAD

**Issue by melissajenner22** [cloudalchemy/ansible-prometheus#306]
**What did you do?**

ansible-playbook -i hosts playbook.yml
```
---
- hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - 101.302.253.160:9090
        - 101.302.253.160:9100
        labels:
          env: devops
```

**Did you expect to see some different?**

http://101.302.253.160:9090/targets

There is an Endpoint: http://status:9090/metrics. The State is "DOWN".
Where is "http://status:9090/metrics" come from?

**Environment**

* Role version:

    `Insert release version/galaxy tag or Git SHA here`

* Ansible version information:

    `ansible --version`
    

* Variables:

```
insert role variables relevant to the issue
```

* Ansible playbook execution Logs:

```
insert Ansible logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Without full configuration, I cannot tell how prometheus was configured. By default port 9090 is where prometheus is exposing its metrics, but from what you attached I cannot see any scrape configuration with address `http://status:9090/metrics`.

**Comment by melissajenner22** [comment]
I git clone https://github.com/cloudalchemy/ansible-prometheus. I did not make any changes.

I figured out status is the Transient hostname of 101.302.253.160. Below is the playbook.yml. In the playbook, I specify 101.302.253.160:9090. I did not specify status:9090. But, http://status:9090/metrics shows as one of endpoints. How do I remove it? status is not FQDN. 

Endpoint                                                        State
http://101.302.253.160:9090/metrics               Up
http://101.302.253.160:9100/metrics               Up
http://101.302.253.161.9100/metrics               Up
http://status:9090/metrics                              DOWN
```
cat playbooks/playbook-prometheus.yml
---
- hosts: all
  roles:
  - ansible-prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - 101.302.253.160:9090
        - 101.302.253.160:9100
        - 101.302.253.161:9100
        labels:
          env: opslab
```
Run the command, ansible-playbook -i hosts/prometheus.hosts playbooks/playbook-prometheus.yml
