### ISSUE TITLE
Attempting to add federation endpoint

### ISSUE THREAD

**Issue by alanmcg** [cloudalchemy/ansible-prometheus#308]
I tried adding federation with some other prometheus servers with the following config:

```
prometheus_scrape_configs:
- job_name: 'federate'
  scrape_interval: 15s

  honor_labels: true
  metrics_path: '/federate'

  params:
  'match[]':
    - '{job="prometheus"}'
    - '{__name__=~"job:.*"}'

  static_configs:
  - targets:
    - 'monitoring.dev.example.net:9090'
    - 'monitoring.uat.example.net:9090'
    - 'monitoring.prod.example.net:9090'
```

But getting the following error:
`fatal: [monitoring]: FAILED! => {"changed": false, "checksum": "e68e2ea1f72f8aeb8769b1949ec862b89459bb99", "exit_status": 1, "msg": "failed to validate", "stderr": "  FAILED: parsing YAML file /home/ubuntu/.ansibl
e/tmp/ansible-tmp-1597304467.1828673-51060614977003/source: yaml: unmarshal errors:\n  line 31: field match[] not found in type config.plain\n", "stderr_lines": ["  FAILED: parsing YAML file /home/ubuntu/.ansible/
tmp/ansible-tmp-1597304467.1828673-51060614977003/source: yaml: unmarshal errors:", "  line 31: field match[] not found in type config.plain"], "stdout": "Checking /home/ubuntu/.ansible/tmp/ansible-tmp-1597304467.
1828673-51060614977003/source\n\n", "stdout_lines": ["Checking /home/ubuntu/.ansible/tmp/ansible-tmp-1597304467.1828673-51060614977003/source", ""]} `

Using latest version of the role and ansible 2.9.6

Is this particular feature not currently supported by the role?
