### ISSUE TITLE
prometheus_scrape_configs changes line order

### ISSUE THREAD

**Issue by webchi** [cloudalchemy/ansible-prometheus#310]
Looks like `to_nice_yaml` shuffle lines
**What happened?**
```
scrape_configs:
  - dockerswarm_sd_configs:
    - host: unix:///var/run/docker.sock
      role: nodes
    job_name: docker
  - job_name: prometheus
    static_configs:
    - targets:
      - 10.0.10.7:9090
```

**Did you expect to see some different?**
```
scrape_configs:
  - job_name: docker
    dockerswarm_sd_configs:
    - host: unix:///var/run/docker.sock
      role: nodes
    
  - job_name: prometheus
    static_configs:
    - targets:
      - 10.0.10.7:9090
```

**How to reproduce it (as minimally and precisely as possible)**:
```
  vars:
    prometheus_scrape_configs:
      - job_name: docker
        dockerswarm_sd_configs:
          - host: unix:///var/run/docker.sock
            role: nodes
      - job_name: prometheus
        static_configs:
          - targets:
              - "{{ ansible_default_ipv4.address }}:9090"
```

**Environment**

* Role version:

2.15.5

* Ansible version information:

ansible 2.9.13
