### ISSUE TITLE
Role fails on 'Fail when file_sd targets are not defined in scrape_configs' while using consul_sd

### ISSUE THREAD

**Issue by YWatchman** [cloudalchemy/ansible-prometheus#365]
**What happened?**
Fails on assertion check for file_sd which is not in use for specific target.

**Did you expect to see some different?**
It explicitly checks for file_sd, while I'm trying to implement consul_sd

**How to reproduce it (as minimally and precisely as possible)**:
Configure consul_sd

**Environment**
Debian Buster

* Role version:
2.15.5

* Ansible version information:
```
ansible 2.10.8
  config file = /home/yvan/.ansible.cfg
  configured module search path = ['/home/yvan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

* Variables:

```
prometheus_scrape_configs:
   ...
    # Consul service discovery
    - job_name: node-exporter
      scrape_interval: 15s
      honor_labels: true
      consul_sd_configs:
        - services: [node-exporter]

prometheus_targets:
  node-exporter:
    - targets:
        "{{ groups['...'] | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '$', ':9100') | list }}"
  alertmanager:
    - targets:
        "{{ groups['...'] | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '$', ':9093') | list }}"
```

* Ansible playbook execution Logs:

```
TASK [cloudalchemy.prometheus : Fail when file_sd targets are not defined in scrape_configs] ***************************************************************************************************
failed: [....] (item={'key': 'node-exporter', 'value': [{'targets': ['....:9100', '....:9100', '...:9100']}]}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "node-exporter", "value": [{"targets": ["....:9100", "...:9100", "...:9100"]}]}, "msg": "Oh, snap! `node-exporter` couldn't be found in your scrape configs. Please ensure you provided all targets from prometheus_targets in prometheus_scrape_configs\n"}
```
