### ISSUE TITLE
v4.0.0 seems to have disappeared from galaxy

### ISSUE THREAD

**Issue by twbecker** [cloudalchemy/ansible-prometheus#387]
Trying to install version 4.0.0 yields the following as of today:

[WARNING]: - cloudalchemy.prometheus was NOT installed successfully: - the specified version (4.0.0) of cloudalchemy.prometheus was
not found in the list of available versions

**Comment by keatz55** [comment]
Experiencing the same.

**Comment by msf1t** [comment]
Same issue here...

**Comment by michaelkebe** [comment]
Same issue here, but we are using 3.0.0, which seems to disappeared as well.

**Comment by michaelkebe** [comment]
I cloned this github repository to a local git repository to make it work. Here is the roles/requirements.yml:

```
roles:
  - name: cloudalchemy.prometheus
    version: 3.0.0
    scm: git
    src: https://our.local.git.repo/ansible-prometheus.git

```

I think you can change the src url to https://github.com/cloudalchemy/ansible-prometheus.git but I haven't tested it.
