### ISSUE TITLE
relabel_configs in prometheus_scrape_configs

### ISSUE THREAD

**Issue by teisho** [cloudalchemy/ansible-prometheus#395]
**What did you do?**
I tried to add `relabel_configs:` to `prometheus_scrape_configs:` for a[ iperf3 exporter](https://github.com/edgard/iperf3_exporter).

```
  prometheus_scrape_configs:
    - job_name: 'iperf3'
      metrics_path: /probe
      static_configs:
        - targets:
            - 123.123.123.123
      params:
        port: ['5201']
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 10.0.1.19:9579  # The iPerf3 exporter's real hostname:port.
```
Result in  `prometheus.yml` is:
```
scrape_configs:
  - job_name: iperf3
    metrics_path: /probe
    params:
      port:
      - '5201'
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: 10.0.1.19:9579
      target_label: __address__
    static_configs:
    - targets:
      - 123.123.123.123
```
If I insert the code from the [iperf3_exporter ](https://github.com/edgard/iperf3_exporter) README by hand into `prometheus.yml`, it works.

**Environment**

* Role version:

    `cloudalchemy.prometheus (4.0.0)`

* Ansible version information:

    `ansible --version`
```
    ansible [core 2.13.1]
   […]
  python version = 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
  jinja version = 3.1.2
  libyaml = True
```

* Variables:

```
prometheus_scrape_configs:
```
