### ISSUE TITLE
Updating prometheus_web_config doesn't reload prometheus

### ISSUE THREAD

**Issue by gaeldb** [cloudalchemy/ansible-prometheus#396]
**What happened?**

When adding/updating the parameter `prometheus_web_config`, prometheus is not reloaded and new parameters are not applied.

**Did you expect to see some different?**

`prometheus_web_config` updated should notify a reload

**How to reproduce it (as minimally and precisely as possible)**:
```
---
- hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        - demo.cloudalchemy.org:9100
        labels:
          env: demosite
    prometheus_web_config:
      basic_auth_users:
        prometheus: 'XXXXXXX'

```
Update XXXXX and run again

**Environment**

* Role version:

    `commit 1440ae7db7d`

* Variables:

```
prometheus_web_config
```
