### ISSUE TITLE
Convert scrape_configs to simple attribute tree

### ISSUE THREAD

**Issue by SuperQ** [cloudalchemy/ansible-prometheus#45]
Rather than having a lot of custom templating, the `scrape_configs` section should be a simple tree of attributes that are sent to the config with `to_nice_yaml`

In `defaults/main.yml`:
```yaml
prometheus_scrape_configs:
  - job_name: prometheus
   ...
```

Then in `templates/prometheus.yml.j2`:
```yaml
scrape_configs:
{{ prometheus_scrape_configs | to_nice_yaml }}
```
