### ISSUE TITLE
Allow multiple targets templates files.

### ISSUE THREAD

**Issue by SuperQ** [cloudalchemy/ansible-prometheus#58]
It should be possible to configure multiple targets files with yaml-only syntax.

```yaml
prometheus_targets:
  node:
  - targets:
    - localhost:9100
    labels:
      env: test
      job: node
  other-job:
  - targets:
    - foo:8080
```

Looping over `prometheus_targets` will create target files named after the job key.

**Comment by paulfantom** [comment]
Just to clarify. After creating those files you'll like to load them with file_sd like this:
```yaml
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/*.yml
```

?
